services:
    nginx:
        image: 'nginx'
        ports:
            - '80:80'
#'8000:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/laravel

    php:
        build:
            dockerfile: ./Dockerfiles/php.Dockerfile
        container_name: laravel_app
        volumes:
            - ./:/var/www/laravel


    mysql:
        image: mysql
        ports:
            - "3316:3306"

        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: root

        container_name: laravel_db



    composer:
        build:
            dockerfile: Dockerfiles/composer.Dockerfile
        volumes:
            - ./:/var/www/laravel

    artisan:
        build:
            dockerfile: Dockerfiles/php.Dockerfile
        volumes:
            - ./:/var/www/laravel
        entrypoint: ["php", "/var/www/laravel/artisan"]

    frontend:
        image: node:20
        working_dir: /var/www/laravel
        volumes:
            - ./:/var/www/laravel
        command: sh -c "npm install && npm run build && tail -f /dev/null"




